### ISSUE TITLE
Empty Dashboard

### ISSUE THREAD

**Issue by dkbast** [converge/instapy-dashboard#2]
Im running Instapy on a Raspberry Pi using tmux and schedule (the script is always "running") - I installed the dashboard and was able to start it without any error, when navigating to it I see a blank dashboard like in your screenshot but without any values. My Instapy is configured in "multi account mode" but Im currently running only one account from it. If I can provide any additional info, please let me know.

**Comment by converge** [comment]
hey @dkbast , did you update this file:

https://github.com/converge/instapy-dashboard/blob/master/src/services/server.js

with your INSTAPY_DB_LOCATION ?

**Comment by andreescocard** [comment]
Same here, i updated the file with the instapyRootFolder and INSTAPY_DB_LOCATION exists

**Comment by converge** [comment]
hey guys, just updated it, it should work now.

*have a look on the docs.

**Comment by an0key** [comment]
Have just tried with a fresh install and still seeing a no stats or live logs too. 

Updaate configuration.js with

  instaPyFolder: '/root/pabs/lib/python2.7/site-packages',

Assume this is correct, as looking at server.js it expects the instapy/db/. If I set the above to the actual root folder for instapy the npm doesn't start saying cannot find the DB.

**Comment by an0key** [comment]
OK some tweaking, it looks like the server/api process on 3001, is using IPv6, whereas the rest of the code is expecting to use localhost, and getting a con refused for 127.0.0.1.

To get this up and working I have changed the following in server.js to hardcode the servers IPv4 address, and has then worked. 

http.listen(port, "x.x.x.x")

This has got the dash working, however still getting some origin not allowed messages, I'm not sure I understand the concept of of allowed hosts... it seems to be the hostname used to connect, rather than connecting hosts? Potentially this is why livelogs aren't showing?

**Comment by an0key** [comment]
Similar in the logger, was hardcoded to localhost. Perhaps better to change all those refernces to the settings of configuration.js

**Comment by converge** [comment]
hey @an0key,
I'll answer step by step:

1. instaPyFolder: '/root/pabs/lib/python2.7/site-packages',
-> you shouln't install it as root, and site-packages are for Python packages, it's best to install it on /opt or in your home folder.
2. you will easily be able to set **instaPyFolder** variable correct like ```/home/user/InstaPy``` as an example.
3. are you using Ipv6 ? I'm sorry but I have zero experience with Ipv6
4. there is an example at configuration.js in the comment section for network usage, did you try it ? It will work for local connections. I'm using CORS policy, it restrict access to your data, without CORS anyone could catch your data with a simple ```curl -LO your.ip:30001/get_all_activities```
5. oh!! I didn't see that, going to update it now, thanks!

Thanks a lot for all the information, it's easier for me to keep updating it with good feedback about good/bad points.

**Comment by converge** [comment]
just updated it https://github.com/converge/instapy-dashboard/commit/2f1265c81fb4761f387c96711bd971b791406f02

**Comment by an0key** [comment]
1. Using the install guide as per instapy, using in venv to actually run the scripts, it handles the appropriate permissions then. 
2. Using the guide for the perferred installation of instapy as per their readme. Hence the location I found that differs from your doc. Looking through the code, for the instapy.db and then simply using locate within linux to find where the path should be is how I came to find it. 
3. All servers are dual stack, yes. Even if not using IPv6 on a standard ubuntu install, it will be enabled. Python will listen often on TCP6 only, and therefore connections to the v4 localhost will fail. 
4. I really dont get this... even setting localhost, I can still access from a remote host. I am not sure your code is working as you expect. Happy to test/discuss further with you. However something like UFW/IPtables/firewall should handle port access here or alternatively some authentication.

**Comment by converge** [comment]
Hey @an0key ,

1. I was worried about it, because I saw it some weeks ago also, I checked the docs, couldn't find the docs describing that. I wouldn't recommend install it in site-packages/ but if it's working, it's ok, and it should read the .db file also. The idea is just point the root folder in the configuration file, and the dashboard will read it.
2. I got a bit lost here, could you tell me the full path of your quickstart.py file and instapy.db ?
4. I tested it again, it's working fine, tested in two scenarios:
### allowing only localhost access:
```js
const config = {
  // InstaPy root folder
  instaPyFolder: '/Users/converge/Documents/workspace/InstaPy',
  serverHost: 'http://localhost:3001',
  allowedHosts: ['http://localhost:3000']
}
```
### allowing localhost and local network to access it
```js
const config = {
  // InstaPy root folder
  instaPyFolder: '/Users/converge/Documents/workspace/InstaPy',
  serverHost: 'http://192.168.0.100:3001',
  allowedHosts: ['http://192.168.0.100:3000', 'http://localhost:3000']
}
```

Requesting the user to setup something like a firewall would add complexity layer to the project, still believe Cors management is the best solution here.

**Comment by an0key** [comment]
1. Checkout the preferred install method on the InstaPY readme. This is what will be produced using that process. 

2. I am not using quickstart.py. Location of the script wouldn't make any difference? You're looking at logs/db. My db is located at /root/pabs/lib/python2.7/site-packages/db/instapy.db

3. So allowedHosts is actually allowed hostnames to be used? This is very confusing. Allowed hosts would be read as hosts allowed to connect, not hostnames allowed to be used to connect. Any use of hostname checking (of the server, not client) is pointless. These can trivially be spoofed in the host headers of the request. 

If you're going to continue with that, whilst I think pretty pointless in terms of protection, I would rename serverHost to APIServer, allowedHosts to allowedHostnames, and potentially look at implementing AllowedClientIP or similar. 

An example, if you have a server with http://external.url:3000 and I can connect to that, even if you have only http://localhost:3000 in the allowedHosts, I can just set my hostheaders to spoof being localhost, connect via IP and I would be allowed in.

**Comment by converge** [comment]
1. I see, the process of install InstaPy in a virtualenv is not so clear, I think we can improve it with easier steps.
2. the dashboard follows a folder pattern, that's why I asked about your quickstart file. Installing it as root isn't a good idea also.

just created a quick venv to illustrate how to install/use it:
```bash
➜  workspace virtualenv my_venv_folder
Using base prefix '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/converge/Documents/workspace/my_venv_folder/bin/python3.7
Also creating executable in /Users/converge/Documents/workspace/my_venv_folder/bin/python
Installing setuptools, pip, wheel...
done.
➜  workspace source my_venv_folder/bin/activate
(my_venv_folder) ➜  workspace pwd
/Users/converge/Documents/workspace
(my_venv_folder) ➜  workspace cd my_venv_folder
(my_venv_folder) ➜  my_venv_folder ls -l
total 0
drwxr-xr-x  17 converge  staff  578 29 Nov 09:57 bin
drwxr-xr-x   3 converge  staff  102 29 Nov 09:57 include
drwxr-xr-x   3 converge  staff  102 29 Nov 09:57 lib
(my_venv_folder) ➜  my_venv_folder git clone https://github.com/timgrossmann/InstaPy.git
Cloning into 'InstaPy'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7340 (delta 0), reused 1 (delta 0), pack-reused 7338
Receiving objects: 100% (7340/7340), 77.20 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (4839/4839), done.
(my_venv_folder) ➜  my_venv_folder cd InstaPy
(my_venv_folder) ➜  InstaPy git:(master) ls -l
total 424
-rw-r--r--   1 converge  staff    2285 29 Nov 09:59 CHANGELOG.md
-rw-r--r--   1 converge  staff    3227 29 Nov 09:59 CODE_OF_CONDUCT.md
-rw-r--r--   1 converge  staff   35119 29 Nov 09:59 LICENSE
-rw-r--r--   1 converge  staff      83 29 Nov 09:59 MANIFEST.in
-rw-r--r--   1 converge  staff  108758 29 Nov 09:59 README.md
-rw-r--r--   1 converge  staff   12041 29 Nov 09:59 api.json
drwxr-xr-x   4 converge  staff     136 29 Nov 09:59 assets
-rw-r--r--   1 converge  staff     163 29 Nov 09:59 docker-allinone.yml
-rw-r--r--   1 converge  staff     470 29 Nov 09:59 docker-compose.yml
-rw-r--r--   1 converge  staff     370 29 Nov 09:59 docker-dev.yml
-rw-r--r--   1 converge  staff     334 29 Nov 09:59 docker-prod.yml
-rw-r--r--   1 converge  staff    1307 29 Nov 09:59 docker-swarm.yml
drwxr-xr-x   6 converge  staff     204 29 Nov 09:59 docker_conf
-rw-r--r--   1 converge  staff    1181 29 Nov 09:59 docker_quickstart.py
drwxr-xr-x   8 converge  staff     272 29 Nov 09:59 docs
drwxr-xr-x   3 converge  staff     102 29 Nov 09:59 extensions
drwxr-xr-x   6 converge  staff     204 29 Nov 09:59 icons
drwxr-xr-x  20 converge  staff     680 29 Nov 09:59 instapy
drwxr-xr-x   5 converge  staff     170 29 Nov 09:59 logs
-rw-r--r--   1 converge  staff    2052 29 Nov 09:59 proxy_extension.py
-rw-r--r--   1 converge  staff     952 29 Nov 09:59 quickstart.py
drwxr-xr-x  15 converge  staff     510 29 Nov 09:59 quickstart_templates
-rw-r--r--   1 converge  staff     354 29 Nov 09:59 requirements.txt
drwxr-xr-x   4 converge  staff     136 29 Nov 09:59 scripts
-rw-r--r--   1 converge  staff    2547 29 Nov 09:59 setup.py
drwxr-xr-x   6 converge  staff     204 29 Nov 09:59 tests
-rwxr-xr-x   1 converge  staff     215 29 Nov 09:59 wait-for-selenium.sh
(my_venv_folder) ➜  InstaPy git:(master)
```

3. I think you're right, now we're exposing configuration.js, it should be accessible just from the backend, I'll sleep on it.

**Comment by andreescocard** [comment]
Pulled now, just changed the baseURL from api.js to my ip address on LAN and worked
